# Generated by Django 4.1.7 on 2023-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_catalog_app', '0004_employee_hierarchy_lvl_counter_alter_employee_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hierarchy_lvl_counter',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Уровень иерархии'),
        ),
    ]
