# Generated by Django 4.1.7 on 2023-03-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_catalog', '0003_remove_employee_self_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hierarchy_lvl_counter',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Уровень иерархии'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_catalog.employee', verbose_name='Начальник'),
        ),
    ]
