# Generated by Django 4.1.7 on 2023-03-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_catalog', '0005_alter_employee_hierarchy_lvl_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hierarchy_lvl_counter',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень иерархии'),
        ),
    ]
