# Generated by Django 4.1.7 on 2023-03-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_catalog', '0006_alter_employee_hierarchy_lvl_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(blank=True, limit_choices_to={'hierarchy_lvl_counter__lt': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_catalog.employee', verbose_name='Начальник'),
        ),
    ]
