# Generated by Django 4.1.7 on 2023-03-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_catalog', '0010_remove_employee_chief_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='chief_id',
            new_name='chief',
        ),
    ]
