# Generated by Django 4.1.7 on 2023-03-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_catalog', '0011_rename_chief_id_employee_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chief',
        ),
    ]
